@include('includes.head')
@if(Auth::user())
    @include('includes.auth-header')
    @else
    @include('includes.header')
    @endif
@include('includes.menus')
@yield('content')
@include('includes.footer')